<html>
<head>

<title>North Carolina Chess Association</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta http-equiv="pragma" content="no-cache">
<link rel="stylesheet" href="../website.css" type="text/css">
<style type="text/css">
<!--
.style1 {
	font-size: x-large;
	font-weight: bold;
}
.style3 {font-size: medium; font-weight: bold; }
-->
</style>
</head>

<body bgcolor="#CCFFFF" text="#000000" >
<table style="width: 80%; height: 933px;" border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td rowspan="2" width="143" height="933" valign="top"><a title="I Like Calling North Carolina HOME!!" href="http://www.ncchess.org/index.php"><img src="ncflag.jpg" border="0" alt="" width="130" height="86" /></a>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>



<?PHP
include("includes/include_links.php");
?>

</td>
<td  height="104" align="center" valign="top"><img src="ncca.gif" alt="" align="center" width="558" height="83" /></td>
</tr>
<tr>
<td width=100% valign="top">
<table width= 100% border="1">
<tbody>
</table>
<p align="left"><span class="style1">The 2010 North Carolina Grand Prix</span><br>
  Brought to you by chesscentral.com<br>
</p>
<p>&nbsp;</p>
<p>&nbsp;<span class="style3"><br>
  Official Procedures, Rules, and Regulations<br>
  &nbsp;<br>
  The North Carolina Grand Prix (NCGP) is a seasonal competition somewhat similar to the USCF Grand Prix.&nbsp; Points are awarded by playing in and winning games at participating tournaments.&nbsp; <br>
  The 2010 Grand Prix begins on November 2, 2009 and continues through the 2010 NC Open. <br>
  The North Carolina Grand Prix is open to any NC resident who is a current paid NCCA member. <br>
  To qualify as a NC resident, one must reside in North Carolina for at least six months of the year.&nbsp; Military and college students who meet this requirement will be considered eligible.&nbsp; Participants who relocate will not forfeit previously earned points if this six month requirement is met. <br>
  *Earning NCGP Points:&nbsp; Points are earned by entering and winning games at participating tournaments. Your Grand Prix score for an individual tournament is your final score on the cross table for that event, if it is a one day event. If the event is a two or three day event, your Grand Prix score is your final score on the cross table x2. For each one day tournament with over 50% of the schedule completed, the player receives one bonus point. For each two/three day event with over 50% of the schedule completed, the player receives 2 bonus points. Points accumulate throughout the year and the prize fund is paid out accordingly.<br>
  The money part of the prize fund is generated by a $1.00 fee per adult player (and per participating scholastic player) at NCGP tournaments.&nbsp; Tournament organizers at participating tournaments and the NCCA share in the responsibility for generating this prize fund as outlined below. &nbsp;<br>
  &nbsp;<br>
  *Participating tourneys:  The following is the criteria to qualify a participating tourney:<br>
  1) The tourney must be held in the State of North Carolina.<br>
  2) It must be open to all NCCA and USCF members. <br>
  3) It must be USCF rated and follow all rules and guidelines customary for USCF events.<br>
  4) The organizer must contribute .75 cents to the prize fund for every participating player (see below for participating player criteria). This money is due and payable to the NCCA within seven days after the tournament. Funds should be sent to the Secretary/Treasurer at the address listed on the NCCA website. <br>
  5) Participating tournaments must require NCCA Membership for all NC adult players.&nbsp; Any player nineteen years or older will be considered an adult.&nbsp; If an adult player inadvertently finishes a tournament without paying NCCA dues, this will be deducted from any tournament prize.&nbsp;<br>
  6) The tournament must be approved by the NCCA board as a Grand Prix event. <br>
  7) Weekday tournaments are not eligible for the Grand Prix.<br>
  8) The tourney must be advertised on the &ldquo;Tournaments&rdquo; page of nc-chess.com for a minimum of 14 days prior to the tournament date.<br>
  * Participating players: The following is the criteria for a participating player:<br>
  1) Must be a member in good standing with the USCF and NCCA<br>
  2) Scholastic players have a choice of whether to participate.&nbsp; Scholastic players who have not remitted NCCA membership dues may do so within 30 days of a win to keep any potential points they would have earned.&nbsp; Thereafter, such points shall expire.<br>
  *Prize fund:  Prizes are provided by ChessCentral.com and the funding system alluded to above. Prizes for the 2010 North Carolina Grand Prix are as follows:<br>
  1st   50% of the prize money + a $350 Gift Certificate from ChessCentral.com<br>
  2nd 25% of the prize money + a $250 Gift Certificate from ChessCentral.com<br>
  3rd 15% of the prize money + a $100 Gift Certificate from ChessCentral.com<br>
  Most Improved 10% of the prize money + a $50 Gift Certificate from ChessCentral.com<br>
  Most active: A wood &ldquo;Duke&rdquo; Style chess set from ChessCentral.com ( a $129 value)&nbsp;<br>
  In addition to the regular prize fund, ChessCentral.com has agreed to provide an additional $50 Gift Certificate to each participating club with at least 20 members and a website. This prize will go to the club member with the highest point total in the NCGP. This prize can be won in addition to any prize qualified for above.<br>
</span></p>
<p class="style3">Additional Rules and Guidelines: <br>
  A. &ldquo;Most Improved&rdquo; determined by using as a starting point the player&rsquo;s regular USCF rating on the November 2009 supplement and calculating the point differential with the post-tournament rating of the 2010 NC Open.<br>
  B. &ldquo;Most Active&rdquo; determined by adding up the number of games played, regardless of result, in participating NCGP tourneys.<br>
  C. &ldquo;Most Improved&rdquo; and &ldquo;Most Active&rdquo; prizes may be won in addition to a prize for a 1st, 2nd, or 3rd place finish.<br>
  D. The cash portion of the prize fund is generated by the .75 cents per player per tourney paid by the organizing affiliate, which is matched by .25 cents per player per tourney by the NCCA. The other portion of the prize fund is contributed by ChessCentral.com<br>
  E. The NCCA President will be responsible for determining and certifying the final standings.&nbsp; The points tally may be maintained by the NCCA President or a designee.&nbsp; <br>
  F.&nbsp; Prizes will be awarded within no more than 30 days of the end of each season.&nbsp;&nbsp;&nbsp;&nbsp; <br>
  G.&nbsp; Points are provisional until funding is received by the NCCA, and the USCF rating report is up.&nbsp; &nbsp;<br>
  H.&nbsp; The NCCA reserves the right to make minor alterations to the procedures, rules, and regulations. The NCCA will be solely responsible for designating Grand Prix status for tournaments. The NCCA reserves the right to settle any dispute arising as a result of this series, and their decision will be final.&nbsp; </p></td>
</tr>
</tbody>
</table>
</body>
</html>
